### ISSUE TITLE
Set up for typescript conversion

### ISSUE THREAD

**Issue by the-pat** [the-pat/tokybook-dl#16]

**Comment by jakehamtexas** [comment]
Ooowee :) I'll grab this one. I favor a two-phase approach, if it works for you: 

1. Add `tsconfig.json` with `allowJs: true`, create build and run scripts to suite
2. Do the conversion itself and remove `allowJs`.

This is a pretty small project at the moment, so it might be reasonable to do it all in one PR. What do you think? I'll leave it to you, if we agree, I'll create an issue for the conversion work and retitle this issue with the Typescript setup notion. I can get started this week.

**Comment by the-pat** [comment]
That works for me!

**Comment by jakehamtexas** [comment]
- [ ] Add `tsconfig.json`
- [ ] Add linting for `.ts`
- [ ] Add scripts for build and run
- [ ] Add ts-node
- [ ] Add missing typescript conversion libraries, a la `ts-jest` if applicable
